-- SQL na Pratica | Laboratorio inicial | PostgreSQL 18
-- Execute em um banco de estudos vazio. Nao apaga objetos existentes.
-- Uma segunda execucao falha se o schema ja existir; use outro banco vazio.
BEGIN;
CREATE SCHEMA sql_pratica;
SET LOCAL search_path TO sql_pratica, public;

CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL CHECK (btrim(nome) <> '')
);

CREATE TABLE contas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuarios (id),
    nome TEXT NOT NULL CHECK (btrim(nome) <> ''),
    UNIQUE (usuario_id, nome)
);

CREATE TABLE categorias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    tipo TEXT NOT NULL CHECK (tipo IN ('receita', 'despesa')),
    UNIQUE (id, tipo)
);

CREATE TABLE lancamentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id INTEGER NOT NULL REFERENCES contas (id),
    categoria_id INTEGER NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('receita', 'despesa')),
    descricao TEXT NOT NULL CHECK (btrim(descricao) <> ''),
    valor NUMERIC(12,2) NOT NULL
        CHECK (valor > 0 AND valor <> 'NaN'::NUMERIC),
    data_competencia DATE NOT NULL,
    data_liquidacao DATE,
    FOREIGN KEY (categoria_id, tipo) REFERENCES categorias (id, tipo)
);

CREATE TABLE orcamentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuarios (id),
    categoria_id INTEGER NOT NULL,
    tipo TEXT NOT NULL DEFAULT 'despesa' CHECK (tipo = 'despesa'),
    mes_referencia DATE NOT NULL CHECK (EXTRACT(DAY FROM mes_referencia) = 1),
    valor_limite NUMERIC(12,2) NOT NULL
        CHECK (valor_limite > 0 AND valor_limite <> 'NaN'::NUMERIC),
    FOREIGN KEY (categoria_id, tipo) REFERENCES categorias (id, tipo),
    UNIQUE (usuario_id, categoria_id, mes_referencia)
);
COMMIT;
